"""Voice notes: the shared extractor fixture, the note sidecar, and the two
Library behaviours that touch it (remove GC, dedupe merge).

Contract: docs/voice-notes.md. The extractor half is driven by
tests/fixtures/note_extraction.json — the SAME file the Swift core's
NoteExtractorTests loads — so a disagreement between the cores shows up here as
a failing case rather than as a silent divergence on the iPad.

The sidecar half pins the interop bytes: the exact key set, explicit nulls,
canonical order, the §1.2 schema gate, and one golden document that was
generated by BOTH cores and compared as parsed JSON (identical), so this file
also stands as the recorded evidence of that comparison.

No microphone, no device, no network: the extractor is pure and the sidecar is
a file.
"""
import json
import shutil
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from microfreak import protocol as p
from microfreak.errors import (EntryNotFoundError, IntegrityError,
                               LibraryCorruptError)
from microfreak.library import Library
from microfreak.model import Category, Preset, Verdict
from microfreak.notes import (NOTE_SCHEMA, NoteDocument, NoteProposal,
                              NoteProposals, NoteSource, PresetNote,
                              canonical_order, note_document_from_json,
                              note_document_to_json, note_from_json,
                              note_to_json)
from microfreak.vocab import (CARRIERS, CHARACTERISTIC_KEYS, CHARACTERISTICS,
                              LEXICON, MAX_KEY_TOKENS, TYPE_KEYS,
                              VERDICT_KEYS, MatchKind,
                              alphabetic_token_count, extract,
                              meets_content_gate, segment_verdict, tokenize)

FIXTURE = Path(__file__).resolve().parent / "fixtures" / "note_extraction.json"

# The 18 Arturia characteristics, docs/arturia-taxonomy.md, written exactly as
# they appear in LibraryEntry.tags. Duplicated here on purpose: if someone edits
# the lexicon's canonical values, this list is the independent witness.
ARTURIA_CHARACTERISTICS = [
    "Acid", "Aggressive", "Ambient", "Bizarre", "Bright", "Complex", "Dark",
    "Digital", "Ensemble", "Funky", "Hard", "Long", "Noise", "Quiet", "Short",
    "Simple", "Soft", "Soundtrack",
]

# The §1.4 key set, exactly. A key added on either side without a schema bump is
# a silent interop break, so the on-disk shape is asserted, not just parsed.
NOTE_KEYS = {"id", "recorded_at", "source", "text", "text_corrected", "locale",
             "session_id", "audio_start", "audio_end", "device_identity",
             "proposals"}
PROPOSAL_KEYS = {"value", "span", "confidence", "accepted"}

META = bytes(9)


def blob7(seed: int) -> bytes:
    out = bytearray()
    x = (seed % 126) + 1
    while len(out) < p.BLOB_SIZE:
        x = (x * 75 + 74) % 127
        out.append(x)
    return bytes(out[:p.BLOB_SIZE])


def note(text: str, *, note_id: str, recorded_at: str, audio_start: float,
         audio_end=None, source: NoteSource = NoteSource.VOICE,
         session: str = "31d0b6c58f9e4a7d8b2c1e0f4a6d8b3c") -> PresetNote:
    """A note with every non-deterministic field pinned, so a test can compare
    whole documents."""
    return PresetNote(id=note_id, recorded_at=recorded_at, source=source,
                      text=text, text_corrected=None, locale="en-US",
                      session_id=session, audio_start=audio_start,
                      audio_end=audio_end, device_identity="hardware",
                      proposals=extract(text))


# ---------------------------------------------------------------- extractor

def test_fixture(cases) -> None:
    """Every shared case, exactly. The fixture is the definition of correct
    (§5.3): a disagreement between the cores is a missing fixture case, never a
    judgement call."""
    failures = []
    for c in cases:
        got = extract(c["transcript"])
        actual = {
            "verdict": got.verdict.value if got.verdict else None,
            "category": got.category.value if got.category else None,
            "tags": list(got.tag_values),
        }
        if actual != c["expected"]:
            failures.append(f"{c['id']}\n    want {c['expected']}\n    got  {actual}"
                            f"\n    why  {c['why']}")
    assert not failures, "extractor disagrees with the shared fixture:\n  " \
        + "\n  ".join(failures)
    print(f"PASS  extractor: {len(cases)}/{len(cases)} shared fixture cases")


def test_fixture_proposal_shape(cases) -> None:
    """Beyond the values the fixture pins: every emitted proposal must come from
    the closed set (§1.6), carry a §2.8 tier confidence, and its span must
    address the VERBATIM transcript — not the normalized form."""
    verdict_slugs = {v.slug for v in Verdict} - {"unrated"}
    category_slugs = {c.slug for c in Category} - {"uncategorized"}
    tiers = {0.9, 0.8, 0.7}
    seen = 0
    for c in cases:
        text = c["transcript"]
        got = extract(text)
        for kind, proposal in (("verdict", got.verdict), ("category", got.category)):
            if proposal is None:
                continue
            pool = verdict_slugs if kind == "verdict" else category_slugs
            assert proposal.value in pool, (c["id"], kind, proposal.value)
        for t in got.tags:
            assert t.value in ARTURIA_CHARACTERISTICS, (c["id"], t.value)
        for proposal in [got.verdict, got.category, *got.tags]:
            if proposal is None:
                continue
            seen += 1
            assert proposal.confidence in tiers, (c["id"], proposal.confidence)
            assert proposal.accepted is False, c["id"]
            span = proposal.span_text(text)
            assert span is not None and span.strip() == span and span, (c["id"], span)
            # the span is a slice of the ORIGINAL text, so it round-trips
            assert text[proposal.span_start:proposal.span_end] == span
    assert seen > 40, seen
    print(f"PASS  proposals: {seen} closed-set values, tier confidences, "
          "verbatim spans")


def test_lexicon_integrity() -> None:
    """The tables themselves: no key longer than 3 tokens (the scan only ever
    tries 3), no key claimed by two lexicons (which would make the §2.4 tie
    order load-bearing in a way no fixture case covers), and canonical values
    drawn only from the three closed sets."""
    for table, name in ((VERDICT_KEYS, "verdict"), (TYPE_KEYS, "type"),
                        (CHARACTERISTIC_KEYS, "characteristic")):
        for value, keys in table.items():
            for key in keys:
                assert key == key.lower().strip(), (name, key)
                assert 1 <= len(key.split(" ")) <= MAX_KEY_TOKENS, (name, key)
    for key in CARRIERS:
        assert 1 <= len(key.split(" ")) <= MAX_KEY_TOKENS, key
        assert key == key.lower().strip(), key
    claimed = {}
    for table, kind in ((VERDICT_KEYS, MatchKind.VERDICT),
                        (TYPE_KEYS, MatchKind.CATEGORY),
                        (CHARACTERISTIC_KEYS, MatchKind.CHARACTERISTIC)):
        for keys in table.values():
            for key in keys:
                assert key not in claimed, f"{key!r} in two lexicons"
                claimed[key] = kind
    assert set(LEXICON) == set(claimed)
    assert set(VERDICT_KEYS) == {v.slug for v in Verdict} - {"unrated"}
    assert set(TYPE_KEYS) == {c.slug for c in Category} - {"uncategorized"}
    assert CHARACTERISTICS == ARTURIA_CHARACTERISTICS
    print(f"PASS  lexicons: {len(LEXICON)} unique keys, {len(CARRIERS)} carriers, "
          "closed canonical sets")


def test_tokenize_spans() -> None:
    """§2.2: trailing punctuation is outside the span, and a contraction's
    pieces share the range of the single original token."""
    toks = tokenize("nice dark pad, bit too noisy, keep")
    assert [t.text for t in toks] == ["nice", "dark", "pad", "bit", "too",
                                      "noisy", "keep"]
    assert (toks[2].start, toks[2].end) == (10, 13)     # 'pad', not 'pad,'
    toks = tokenize("don't keep it")
    assert [t.text for t in toks] == ["do", "not", "keep", "it"]
    assert (toks[0].start, toks[0].end) == (0, 5)
    assert (toks[1].start, toks[1].end) == (0, 5)       # both pieces = "don't"
    # A CURLY apostrophe does NOT expand: the §2.1 contraction table's keys are
    # written with the ASCII apostrophe, so `it’s` falls through to step 4 and
    # joins to `its`. Both cores do exactly this (verified against the Swift
    # tokenizer), which is what parity requires; widening the table to the
    # typographic form would be a two-core change plus a fixture case.
    assert [t.text for t in tokenize("it’s 8 bit")] == ["its", "8", "bit"]
    assert [t.text for t in tokenize("it's 8 bit")] == ["it", "is", "8", "bit"]
    # digits survive normalization (§2.1 step 5): 303, 808, 8 bit
    assert [t.text for t in tokenize("classic 303")] == ["classic", "303"]
    # NFC: a decomposed e-acute is one code point after normalization
    assert [t.text for t in tokenize("éclat")] == ["éclat"]
    print("PASS  tokenize: spans exclude dropped punctuation, contractions share "
          "one range")


def test_locale_gate_and_content_gate() -> None:
    """§2.0 locale gate (advisory layer only) and §2.9 empty-note gate (the
    CALLER's job, deliberately not extract's)."""
    assert extract("dark pad, keep", locale="fr-FR") == NoteProposals.EMPTY
    assert extract("dark pad, keep", locale="en-GB").verdict is not None
    assert extract("dark").tag_values == ("Dark",)      # extraction still fires
    assert not meets_content_gate("dark")               # but it is never stored
    assert not meets_content_gate("303")                # a digit is not alphabetic
    assert alphabetic_token_count("303 8 bit") == 1
    assert meets_content_gate("dark pad")
    print("PASS  locale gate skips only the advisory layer; content gate needs "
          "two alphabetic tokens")


def test_segment_verdict() -> None:
    """§2.7 segment scope: the last utterance's verdict, or any <=4-token
    utterance's, latest wins."""
    long_desc = "keep this preset for the deep bass texture"
    assert extract(long_desc).verdict is None            # positional rule
    assert segment_verdict([long_desc]) is None
    # a bare 'keep' said EARLY in a long segment still counts
    v = segment_verdict(["keep", "and it has a really nice long release on it"])
    assert v is not None and v.value == "keep"
    # the last utterance's verdict wins when it is later
    v = segment_verdict(["keep", "on reflection this one is meh"])
    assert v is not None and v.value == "meh"
    assert segment_verdict([]) is None
    print("PASS  segment verdict: last utterance or any <=4-token one, latest wins")


def test_proposal_helpers() -> None:
    """The core types the app binds to. `unrated`/`uncategorized` are never
    proposed, so an unparseable value must yield None and never a false
    default."""
    got = extract("nice dark pad, bit too noisy, keep")
    assert got.verdict_value is Verdict.KEEP
    assert got.category_value is Category.PAD
    assert got.tag_values == ("Dark", "Noise")
    assert not got.is_empty and NoteProposals.EMPTY.is_empty
    bogus = NoteProposals(verdict=NoteProposal("nonsense", 0, 1, 0.9),
                          category=NoteProposal("nonsense", 0, 1, 0.9))
    assert bogus.verdict_value is None and bogus.category_value is None
    accepted = got.verdict.accepting()
    assert accepted.accepted and not got.verdict.accepted
    assert accepted.value == got.verdict.value and accepted.span_start == got.verdict.span_start
    assert got.verdict.span_text("short") is None       # span off the end
    print("PASS  proposal helpers: closed-set parse, accepting() copies, span "
          "guards")


# ------------------------------------------------------------------ sidecar

def test_codec_round_trip() -> None:
    """§1.4 on-disk shape: the exact key set, explicit nulls, and a lossless
    round-trip through the codec."""
    n = note("nice dark pad, bit too noisy, keep",
             note_id="9f2c4a1e7b0d4f6a8c3e5d7b9a1c2e4f",
             recorded_at="2026-09-02T14:03:11", audio_start=12.48,
             audio_end=15.921)
    d = note_to_json(n)
    assert set(d) == NOTE_KEYS, set(d) ^ NOTE_KEYS
    assert d["text_corrected"] is None                  # explicit null
    assert set(d["proposals"]) == {"verdict", "category", "tags"}
    assert set(d["proposals"]["verdict"]) == PROPOSAL_KEYS
    assert d["proposals"]["verdict"]["span"] == [30, 34]
    assert note_from_json(d) == n
    typed = PresetNote(id="5b1e8d3c7a094f2b6d8e0c4a2f7b9d13",
                       recorded_at="2026-09-02T14:07:44", source=NoteSource.TYPED,
                       text="revisit with the filter opened up",
                       text_corrected=None, locale="en-US",
                       session_id="31d0b6c58f9e4a7d8b2c1e0f4a6d8b3c",
                       audio_start=285.0, audio_end=None,
                       device_identity="hardware",
                       proposals=extract("revisit with the filter opened up"))
    td = note_to_json(typed)
    assert td["audio_end"] is None and td["source"] == "typed"
    assert td["proposals"]["category"] is None and td["proposals"]["tags"] == []
    assert note_from_json(td) == typed
    doc = NoteDocument(schema=NOTE_SCHEMA, entry_id="c78e5cd14acb49b1bf08b66d609a714a",
                       notes=(n, typed))
    assert note_document_from_json(note_document_to_json(doc)) == doc
    # a note with no id or no text names nothing and says nothing
    for missing in ("id", "text"):
        broken = dict(d)
        broken.pop(missing)
        try:
            note_from_json(broken, path="x")
            raise AssertionError(f"missing {missing} must be corrupt")
        except LibraryCorruptError:
            pass
    print("PASS  codec: exact key set, explicit nulls, lossless round-trip")


def test_swift_parity_document() -> None:
    """The recorded cross-core comparison. This document was produced by the
    SWIFT core (Library.appendNote on a temp library, entry id masked) and is
    compared against what this core writes for the same inputs. The two parse to
    the same JSON object — same keys, same spans, same tier confidences, same
    explicit nulls — which is §5.1's round-trip obligation.

    Textual differences that do NOT matter and are deliberately not asserted:
    JSONSerialization sorts keys and writes `285` where Python writes `285.0`.
    Both parse to the same value; §1.3 pins the ORDER OF `notes`, not the byte
    order of the keys."""
    n = note("nice dark pad, bit too noisy, keep",
             note_id="9f2c4a1e7b0d4f6a8c3e5d7b9a1c2e4f",
             recorded_at="2026-09-02T14:03:11", audio_start=12.48,
             audio_end=15.921)
    typed = PresetNote(id="5b1e8d3c7a094f2b6d8e0c4a2f7b9d13",
                       recorded_at="2026-09-02T14:07:44", source=NoteSource.TYPED,
                       text="revisit with the filter opened up",
                       text_corrected="revisit with the filter open",
                       locale="en-US",
                       session_id="31d0b6c58f9e4a7d8b2c1e0f4a6d8b3c",
                       audio_start=285.0, audio_end=None,
                       device_identity="hardware",
                       proposals=extract("revisit with the filter opened up"))
    doc = NoteDocument(schema=1, entry_id="<ENTRY>", notes=(n, typed))
    assert json.loads(json.dumps(note_document_to_json(doc))) == SWIFT_GOLDEN
    assert note_document_from_json(SWIFT_GOLDEN) == doc      # and reads it back
    # the no-audio rule: no field anywhere may hold audio or a path to it
    blob = json.dumps(SWIFT_GOLDEN).lower()
    for forbidden in ("audio_path", "audio_url", "audio_data", "recording",
                      ".wav", ".caf", ".m4a", "base64"):
        assert forbidden not in blob, forbidden
    print("PASS  parity: the Swift-written sidecar and this core's are the same "
          "JSON document")


def test_library_sidecar(work: Path) -> None:
    lib = Library.create(work / "lib")
    e = lib.add(Preset(name="A", blob=blob7(1), meta=META))
    other = lib.add(Preset(name="B", blob=blob7(2), meta=META))

    # a missing file means ZERO notes, never an error, and nothing is created
    assert lib.notes(e.id) == [] and lib.note_document(e.id) is None
    assert not (work / "lib" / "notes").exists()
    # a sidecar with no entry is ignored, not resurrected
    assert lib.notes("deadbeef" * 4) == []

    later = note("bright organ, quite quiet in the mix, try it later",
                 note_id="b" * 32, recorded_at="2026-09-02T14:09:00",
                 audio_start=40.0, audio_end=44.25)
    earlier = note("huge cinematic pad, long release, quite dark, definitely a keeper",
                   note_id="a" * 32, recorded_at="2026-09-02T14:03:11",
                   audio_start=12.48, audio_end=18.0)
    lib.append_note(e.id, later)
    lib.append_note(e.id, earlier)

    # §1.3 canonical order: ascending recorded_at (written, not just returned)
    on_disk = json.loads((work / "lib" / "notes" / f"{e.id}.json").read_text())
    assert on_disk["schema"] == 1 and on_disk["entry_id"] == e.id
    assert [n["id"] for n in on_disk["notes"]] == ["a" * 32, "b" * 32]
    assert [n.id for n in lib.notes(e.id)] == ["a" * 32, "b" * 32]
    assert lib.notes(other.id) == []                       # per-entry, not shared
    assert Library.open(work / "lib").notes(e.id) == lib.notes(e.id)

    # ties: same recorded_at -> audio_start, then id
    tie_a = note("dark pad", note_id="f" * 32, recorded_at="2026-01-01T00:00:00",
                 audio_start=2.0, audio_end=3.0)
    tie_b = note("bright pad", note_id="0" * 32, recorded_at="2026-01-01T00:00:00",
                 audio_start=1.0, audio_end=2.0)
    tie_c = note("soft pad", note_id="1" * 32, recorded_at="2026-01-01T00:00:00",
                 audio_start=1.0, audio_end=2.0)
    assert [n.id for n in canonical_order([tie_a, tie_c, tie_b])] == \
        ["0" * 32, "1" * 32, "f" * 32]

    # replace_notes is the "move to previous preset" half of §4
    lib.replace_notes(other.id, [earlier])
    lib.replace_notes(e.id, [later])
    assert [n.id for n in lib.notes(other.id)] == ["a" * 32]
    assert [n.id for n in lib.notes(e.id)] == ["b" * 32]
    # audio offsets are session-relative, so they do NOT change on a move
    assert lib.notes(other.id)[0].audio_start == 12.48

    # an empty list deletes the file rather than leaving an empty document
    lib.replace_notes(other.id, [])
    assert not (work / "lib" / "notes" / f"{other.id}.json").exists()
    assert lib.notes(other.id) == []
    lib.delete_notes(other.id)                             # idempotent

    # unknown entry: reads are silent, writes raise
    for call in (lambda: lib.append_note("nope", later),
                 lambda: lib.replace_notes("nope", [later])):
        try:
            call()
            raise AssertionError("write to an unknown entry must raise")
        except EntryNotFoundError:
            pass
    print("PASS  sidecar: missing file = zero notes, canonical order on disk, "
          "replace/delete, unknown entry")


def test_schema_gate_and_corruption(work: Path) -> None:
    lib = Library.create(work / "gate")
    e = lib.add(Preset(name="A", blob=blob7(3), meta=META))
    lib.append_note(e.id, note("dark pad, keep it", note_id="c" * 32,
                               recorded_at="2026-09-02T15:00:00",
                               audio_start=1.0, audio_end=2.0))
    path = work / "gate" / "notes" / f"{e.id}.json"

    # §1.2: a NEWER schema is readable but must never be rewritten
    data = json.loads(path.read_text())
    data["schema"] = 99
    data["notes"][0]["future_key"] = "written by a later core"
    path.write_text(json.dumps(data, indent=2))
    doc = lib.note_document(e.id)
    assert doc is not None and doc.schema == 99 and doc.is_read_only
    assert len(lib.notes(e.id)) == 1                       # still displayable
    for call in (lambda: lib.append_note(e.id, note("x y", note_id="d" * 32,
                                                    recorded_at="2026-09-02T16:00:00",
                                                    audio_start=3.0, audio_end=4.0)),
                 lambda: lib.replace_notes(e.id, [])):
        try:
            call()
            raise AssertionError("a newer schema must refuse the rewrite")
        except IntegrityError:
            pass
    assert json.loads(path.read_text())["notes"][0]["future_key"]   # untouched

    # a present-but-unparseable file raises the collection reader's error
    path.write_text("{not json")
    try:
        lib.notes(e.id)
        raise AssertionError("a torn sidecar must raise")
    except LibraryCorruptError:
        pass
    path.write_text(json.dumps({"schema": 0, "entry_id": e.id, "notes": []}))
    try:
        lib.notes(e.id)
        raise AssertionError("schema 0 must raise")
    except LibraryCorruptError:
        pass
    # §1.1 says deleting an entry deletes its sidecar — no schema gate on delete
    path.write_text(json.dumps({"schema": 99, "entry_id": e.id, "notes": []}))
    lib.remove(e.id)
    assert not path.exists()
    print("PASS  schema gate: newer file readable, never rewritten; corrupt file "
          "raises; delete ungated")


def test_remove_gc(work: Path) -> None:
    lib = Library.create(work / "gc")
    a = lib.add(Preset(name="A", blob=blob7(4), meta=META))
    b = lib.add(Preset(name="B", blob=blob7(5), meta=META))
    for entry in (a, b):
        lib.append_note(entry.id, note("dark pad, keep it", note_id="e" * 32,
                                       recorded_at="2026-09-02T17:00:00",
                                       audio_start=1.0, audio_end=2.0))
    lib.remove(a.id)
    assert not (work / "gc" / "notes" / f"{a.id}.json").exists()
    assert (work / "gc" / "notes" / f"{b.id}.json").exists()
    assert len(lib.notes(b.id)) == 1
    print("PASS  remove(): the entry's sidecar goes with it, its neighbour's "
          "stays")


def test_dedupe_merge(work: Path) -> None:
    """Notes merge like tags, not like slots: two catalog rows for the same
    (sha256, name) were always the same preset, so the loser's notes are folded
    into the survivor rather than dropped."""
    lib = Library.create(work / "dd")
    a = lib.add(Preset(name="X", blob=blob7(6), meta=META))
    b = lib.add(Preset(name="X", blob=blob7(6), meta=META))       # exact dup
    keeper = lib.add(Preset(name="Y", blob=blob7(7), meta=META))  # untouched
    lib.append_note(a.id, note("dark pad, keep it", note_id="a" * 32,
                               recorded_at="2026-09-02T10:00:00",
                               audio_start=1.0, audio_end=2.0))
    lib.append_note(b.id, note("really aggressive bass, way too harsh, never",
                               note_id="b" * 32,
                               recorded_at="2026-09-02T09:00:00",
                               audio_start=5.0, audio_end=8.0))
    lib.append_note(keeper.id, note("bright organ, try it later", note_id="c" * 32,
                                    recorded_at="2026-09-02T11:00:00",
                                    audio_start=9.0, audio_end=10.0))
    assert lib.dedupe() == 1
    merged = lib.notes(a.id)
    # concatenated AND re-sorted into canonical order (b's note is earlier)
    assert [n.id for n in merged] == ["b" * 32, "a" * 32]
    assert not (work / "dd" / "notes" / f"{b.id}.json").exists()
    assert [n.id for n in lib.notes(keeper.id)] == ["c" * 32]
    assert merged[0].proposals.verdict_value is Verdict.NEVER   # provenance intact

    # the §1.2 refusal: one newer sidecar in the group leaves the WHOLE group
    # alone — an unreachable-but-intact file beats a rewritten one
    lib2 = Library.create(work / "dd2")
    c = lib2.add(Preset(name="Z", blob=blob7(8), meta=META))
    d = lib2.add(Preset(name="Z", blob=blob7(8), meta=META))
    lib2.append_note(c.id, note("dark pad, keep it", note_id="a" * 32,
                                recorded_at="2026-09-02T10:00:00",
                                audio_start=1.0, audio_end=2.0))
    lib2.append_note(d.id, note("harsh digital mess, never", note_id="b" * 32,
                                recorded_at="2026-09-02T09:00:00",
                                audio_start=5.0, audio_end=8.0))
    future = work / "dd2" / "notes" / f"{d.id}.json"
    data = json.loads(future.read_text())
    data["schema"] = 99
    future.write_text(json.dumps(data, indent=2))
    assert lib2.dedupe() == 1
    assert [n.id for n in lib2.notes(c.id)] == ["a" * 32]     # not merged
    assert json.loads(future.read_text())["schema"] == 99      # and not destroyed
    print("PASS  dedupe(): losers' notes folded in and re-sorted; a newer "
          "sidecar aborts the merge intact")


def test_merge_bundle_carries_no_notes(work: Path) -> None:
    """A bundled seed has no notes/ — a note records something a user said in an
    audition session and a seed has never been auditioned — and merge_bundle
    mints fresh entry ids anyway, so there is no id under which a foreign
    sidecar could even be addressed."""
    from microfreak.collections import Provenance, ProvenanceKind, PresetCollection
    seed = Library.create(work / "seed")
    preset = Preset(name="S", blob=blob7(9), meta=META)
    ref = seed.store_preset(preset)
    seed.save_collection(PresetCollection.new(
        name="Seed", provenance=Provenance(kind=ProvenanceKind.MANUAL, source="t"),
        slots={0: ref}))
    dest = Library.create(work / "dest")
    assert dest.merge_bundle(seed) == 1
    assert not (work / "dest" / "notes").exists()
    assert all(dest.notes(e.id) == [] for e in dest.entries())
    print("PASS  merge_bundle(): a bundled seed carries no notes and mints none")


def test_trust_rules(work: Path) -> None:
    """§3. `text` is verbatim and immutable; a correction is a sibling; an
    accepted proposal goes to its CANONICAL home and the sidecar only records
    that it was confirmed."""
    lib = Library.create(work / "trust")
    e = lib.add(Preset(name="A", blob=blob7(11), meta=META))
    spoken = "nice dark pad, bit too noisy, keep"
    n = note(spoken, note_id="9" * 32, recorded_at="2026-09-02T18:00:00",
             audio_start=1.0, audio_end=4.0)
    lib.append_note(e.id, n)

    corrected = n.correcting("nice dark pad, a bit too noisy, keep")
    assert corrected.text == spoken                    # the original stays
    assert corrected.text_corrected != corrected.text
    assert corrected.correcting(None).text_corrected is None
    lib.replace_notes(e.id, [corrected])
    assert lib.notes(e.id)[0].text == spoken

    # the entry is untouched until the user accepts through the real setter
    assert lib.entry(e.id).verdict is Verdict.UNRATED
    assert lib.entry(e.id).category is Category.UNCATEGORIZED
    assert lib.entry(e.id).tags == ()
    props = corrected.proposals
    lib.set_verdict(e.id, props.verdict_value)
    lib.set_category(e.id, props.category_value)
    lib.set_tags(e.id, props.tag_values)
    confirmed = corrected.recording_acceptance(NoteProposals(
        verdict=props.verdict.accepting(),
        category=props.category.accepting(),
        tags=tuple(t.accepting() for t in props.tags)))
    lib.replace_notes(e.id, [confirmed])

    # the canonical home is the index — every existing consumer sees it there,
    # with no knowledge that a microphone was involved
    reopened = Library.open(work / "trust")
    entry = reopened.entry(e.id)
    assert entry.verdict is Verdict.KEEP and entry.category is Category.PAD
    assert entry.tags == ("Dark", "Noise")
    index = json.loads((work / "trust" / "index.json").read_text())
    assert index["entries"][0]["verdict"] == "keep"
    assert set(index["entries"][0]) == {"id", "name", "sha256", "meta_hex",
                                        "slot", "added_at", "tags", "category",
                                        "favorite", "verdict"}
    # and deleting notes/ leaves the library exactly as correct as before
    shutil.rmtree(work / "trust" / "notes")
    after = Library.open(work / "trust").entry(e.id)
    assert after == entry
    print("PASS  trust rules: verbatim text, sibling correction, canonical home, "
          "sidecar is provenance only")


def test_atomic_note_ops(work: Path) -> None:
    """`notes()` then `replace_notes()` is a read-modify-write with a gap in it.
    On the Swift side that gap is a real suspension between two actor hops, and
    a note appended in it is silently overwritten by the stale list the caller
    still holds — an unrecoverable loss, because §1.5 keeps no audio. Both cores
    therefore offer the indivisible forms, and both cores' callers use them."""
    lib = Library.create(work / "atomic")
    a = lib.add(Preset(name="A", blob=blob7(12), meta=META))
    b = lib.add(Preset(name="B", blob=blob7(13), meta=META))
    n1 = note("dark pad, keep it", note_id="1" * 32,
              recorded_at="2026-09-02T10:00:00", audio_start=1.0, audio_end=2.0)
    lib.append_note(b.id, n1)

    # mutate_notes: read, transform and rewrite in one step
    lib.mutate_notes(b.id, lambda ns: [
        n.recording_acceptance(NoteProposals(
            verdict=n.proposals.verdict.accepting() if n.proposals.verdict else None,
            category=n.proposals.category, tags=n.proposals.tags))
        for n in ns])
    assert lib.notes(b.id)[0].proposals.verdict.accepted is True
    assert lib.notes(b.id)[0].text == n1.text          # verbatim, untouched

    # move_note appends to the destination FIRST: a destination that cannot be
    # written leaves the note where it was rather than consuming it
    try:
        lib.move_note("1" * 32, b.id, "deadbeef" * 4)
        raise AssertionError("a move into an unknown entry must raise")
    except EntryNotFoundError:
        pass
    assert [n.id for n in lib.notes(b.id)] == ["1" * 32]

    moved = lib.move_note("1" * 32, b.id, a.id)
    assert moved is not None and moved.id == "1" * 32
    assert lib.notes(b.id) == []
    assert [n.id for n in lib.notes(a.id)] == ["1" * 32]
    assert lib.notes(a.id)[0].audio_start == 1.0       # session-relative
    assert lib.move_note("nope", b.id, a.id) is None   # absent is not an error

    # remove_note drops exactly one, idempotently
    lib.append_note(a.id, note("bright lead, try later", note_id="2" * 32,
                               recorded_at="2026-09-02T11:00:00",
                               audio_start=3.0, audio_end=4.0))
    lib.remove_note(a.id, "1" * 32)
    assert [n.id for n in lib.notes(a.id)] == ["2" * 32]
    lib.remove_note(a.id, "1" * 32)
    assert [n.id for n in lib.notes(a.id)] == ["2" * 32]
    print("PASS  atomic ops: mutate_notes, move_note (append first), "
          "remove_note")


def test_malformed_numbers_fall_back() -> None:
    """A hand-edited, truncated or foreign sidecar must never raise a bare
    ValueError/TypeError out of this module, and must read the SAME way in both
    cores: `[1.5, 3.5]` is not a span and `true` is not a number of seconds, so
    both fall back rather than truncating."""
    for bad in ("oops", {"a": 1}, [1], True, None):
        n = note_from_json({"id": "a" * 32, "text": "dark pad, keep it",
                            "audio_start": bad, "audio_end": bad})
        assert n.audio_start == 0.0, bad
        assert n.audio_end is None, bad
    ok = note_from_json({"id": "a" * 32, "text": "dark pad", "audio_start": 3,
                         "audio_end": 4.5})
    assert ok.audio_start == 3.0 and ok.audio_end == 4.5
    doc = note_document_from_json({
        "schema": 1, "entry_id": "e", "notes": [{
            "id": "a" * 32, "text": "dark pad, keep it",
            "proposals": {"verdict": {"value": "keep", "span": [1.5, 3.5],
                                      "confidence": True, "accepted": False},
                          "category": None, "tags": []}}]})
    v = doc.notes[0].proposals.verdict
    assert (v.span_start, v.span_end) == (0, 0)
    assert v.confidence == 0.0
    assert v.span_text(doc.notes[0].text) is None    # (0, 0) addresses nothing
    print("PASS  malformed numbers: both cores fall back identically, nothing "
          "raises out of the module")


def test_rounding_matches_the_swift_core() -> None:
    """The two cores must write the SAME number. Swift used to scale first
    ((x * 1000).rounded(.toNearestOrEven) / 1000), which manufactures a tie the
    true binary value does not have: 0.0685 — frame 3288 at 48 kHz — is really
    0.068500000000000005 and rounds up, while the scaled product lands on
    exactly 68.5 and banker's rounding took it down."""
    from microfreak.notes import _round3
    assert _round3(0.0685) == 0.069
    assert _round3(0.2055) == 0.205
    assert _round3(3288 / 48000) == 0.069
    assert _round3(12.4812345) == 12.481
    assert round(2.25, 1) == 2.2 and round(2.35, 1) == 2.4    # still half-even
    print("PASS  rounding: audio offsets round the way both cores round")


def test_new_mints_and_extracts() -> None:
    """PresetNote.new mints a uuid4 hex id and a local ISO timestamp shaped like
    added_at, and extracts proposals unless the caller supplies its own."""
    n = PresetNote.new(source=NoteSource.VOICE,
                       text="acid lead, super funky, this is a keeper",
                       locale="en-US", session_id="0" * 32, audio_start=1.5,
                       audio_end=4.25, device_identity="practice:default")
    assert len(n.id) == 32 and n.id == n.id.lower() and "-" not in n.id
    assert len(n.recorded_at) == 19 and n.recorded_at[10] == "T"
    assert n.recorded_at.count(":") == 2 and "+" not in n.recorded_at
    assert n.proposals.verdict_value is Verdict.KEEP
    assert n.proposals.category_value is Category.LEAD
    assert n.proposals.tag_values == ("Acid", "Funky")
    assert n.text_corrected is None
    supplied = PresetNote.new(source=NoteSource.TYPED, text="dark pad, keep",
                              locale="en-US", session_id="0" * 32,
                              audio_start=0.0, audio_end=None,
                              device_identity="none",
                              proposals=NoteProposals.EMPTY)
    assert supplied.proposals.is_empty and supplied.audio_end is None
    assert NoteSource.from_str("typed") is NoteSource.TYPED
    assert NoteSource.from_str("telepathy") is NoteSource.VOICE   # forward-compat
    print("PASS  PresetNote.new: uuid4 hex id, added_at-shaped timestamp, "
          "extraction unless supplied")


# The golden document below was produced by the SWIFT core (see
# test_swift_parity_document). Keep it byte-frozen; regenerate it only when the
# schema is bumped in docs/voice-notes.md and BOTH cores are updated.
SWIFT_GOLDEN = {
    "schema": 1,
    "entry_id": "<ENTRY>",
    "notes": [
        {
            "id": "9f2c4a1e7b0d4f6a8c3e5d7b9a1c2e4f",
            "recorded_at": "2026-09-02T14:03:11",
            "source": "voice",
            "text": "nice dark pad, bit too noisy, keep",
            "text_corrected": None,
            "locale": "en-US",
            "session_id": "31d0b6c58f9e4a7d8b2c1e0f4a6d8b3c",
            "audio_start": 12.48,
            "audio_end": 15.921,
            "device_identity": "hardware",
            "proposals": {
                "verdict": {"value": "keep", "span": [30, 34],
                            "confidence": 0.9, "accepted": False},
                "category": {"value": "pad", "span": [10, 13],
                             "confidence": 0.9, "accepted": False},
                "tags": [
                    {"value": "Dark", "span": [5, 9],
                     "confidence": 0.9, "accepted": False},
                    {"value": "Noise", "span": [23, 28],
                     "confidence": 0.7, "accepted": False},
                ],
            },
        },
        {
            "id": "5b1e8d3c7a094f2b6d8e0c4a2f7b9d13",
            "recorded_at": "2026-09-02T14:07:44",
            "source": "typed",
            "text": "revisit with the filter opened up",
            "text_corrected": "revisit with the filter open",
            "locale": "en-US",
            "session_id": "31d0b6c58f9e4a7d8b2c1e0f4a6d8b3c",
            "audio_start": 285.0,
            "audio_end": None,
            "device_identity": "hardware",
            "proposals": {
                "verdict": {"value": "try_later", "span": [0, 7],
                            "confidence": 0.7, "accepted": False},
                "category": None,
                "tags": [],
            },
        },
    ],
}


def run(work: Path) -> None:
    cases = json.loads(FIXTURE.read_text())
    assert len(cases) >= 70, f"the shared fixture shrank: {len(cases)} cases"
    test_fixture(cases)
    test_fixture_proposal_shape(cases)
    test_lexicon_integrity()
    test_tokenize_spans()
    test_locale_gate_and_content_gate()
    test_segment_verdict()
    test_proposal_helpers()
    test_codec_round_trip()
    test_swift_parity_document()
    test_library_sidecar(work)
    test_schema_gate_and_corruption(work)
    test_remove_gc(work)
    test_dedupe_merge(work)
    test_merge_bundle_carries_no_notes(work)
    test_trust_rules(work)
    test_atomic_note_ops(work)
    test_malformed_numbers_fall_back()
    test_rounding_matches_the_swift_core()
    test_new_mints_and_extracts()


def main() -> None:
    work = Path(tempfile.mkdtemp(prefix="mfcap-test-notes-"))
    try:
        run(work)
    finally:
        shutil.rmtree(work, ignore_errors=True)


if __name__ == "__main__":
    main()
