// VectorTests.swift — the golden-vector runner.
//
// The vectors under Fixtures/vectors/ are generated by the Python reference
// implementation and are AUTHORITATIVE: byte-for-byte wire parity. They are
// regenerated with `python3 tools/gen_vectors.py` from the repo root — the
// Swift side never regenerates or reshapes them; it only consumes them.
//
// Every file is {"description": str, "cases": [...]}, with all byte
// sequences space-separated uppercase hex ("F0 00 20 6B ..."). The runner
// enumerates every *.json in the vectors directory and FAILS if a file
// exists that it does not handle — a new vector file can never be silently
// skipped.

import Foundation
import Testing
@testable import FreakCore

private let handledFiles: Set<String> = [
    "expendable.json", "frames.json", "name_replies.json", "read_dump.json",
    "reply_lag.json", "sync_diff.json", "write_burst.json",
]

private var vectorsDir: URL {
    Bundle.module.resourceURL!
        .appendingPathComponent("Fixtures")
        .appendingPathComponent("vectors")
}

private func vectorCases(_ file: String) throws -> [[String: Any]] {
    let data = try Data(contentsOf: vectorsDir.appendingPathComponent(file))
    let obj = try JSONSerialization.jsonObject(with: data) as! [String: Any]
    return obj["cases"] as! [[String: Any]]
}

private func int(_ c: [String: Any], _ key: String) -> Int {
    (c[key] as! NSNumber).intValue
}

private func optInt(_ c: [String: Any], _ key: String) -> Int? {
    (c[key] as? NSNumber)?.intValue
}

private func str(_ c: [String: Any], _ key: String) -> String {
    c[key] as! String
}

private func seqByte(_ c: [String: Any]) -> UInt8 {
    UInt8(int(c, "seq"))
}

private func slotRecords(_ c: [String: Any]) -> [SlotRecord] {
    (c["records"] as! [[String: Any]]).map {
        SlotRecord(slot: int($0, "slot"), name: $0["name"] as? String,
                   sha256: $0["sha256"] as? String, meta: nil, blob: nil)
    }
}

private func expectWireLogMatches(_ log: [WireEntry],
                                  _ transcript: [[String: Any]],
                                  context: String) {
    #expect(log.count == transcript.count,
            "\(context): wire log has \(log.count) entries, transcript \(transcript.count)")
    for (i, (entry, t)) in zip(log, transcript).enumerated() {
        #expect(entry.direction.rawValue == str(t, "dir"),
                "\(context): direction mismatch at entry \(i)")
        #expect(entry.raw == hexBytes(str(t, "frame")),
                "\(context): frame mismatch at entry \(i) (\(str(t, "label")))")
    }
}

@Suite("Golden vectors")
struct VectorTests {

    /// Safety net (§8 principle): every *.json in the vectors directory must
    /// have a runner; a missing expected file fails too.
    @Test func everyVectorFileIsHandled() throws {
        let files = try FileManager.default
            .contentsOfDirectory(atPath: vectorsDir.path)
            .filter { $0.hasSuffix(".json") }
        for f in files where !handledFiles.contains(f) {
            Issue.record("vector file \(f) exists but the runner does not handle it — add a runner")
        }
        #expect(Set(files) == handledFiles)
    }

    // -------------------------------------------------------- frames.json

    @Test func frameBuilders() throws {
        let cases = try vectorCases("frames.json")
        #expect(!cases.isEmpty)
        for c in cases {
            let kind = str(c, "kind")
            let expect = hexBytes(str(c, "frame"))
            switch kind {
            case "read_name_req":
                let got = try FreakProtocol.readNameRequest(seq: seqByte(c),
                                                            slot: int(c, "slot"))
                #expect(got == expect, "read_name_req slot \(int(c, "slot"))")
            case "open_dump_req":
                let got = try FreakProtocol.openDumpRequest(seq: seqByte(c),
                                                            slot: int(c, "slot"))
                #expect(got == expect, "open_dump_req slot \(int(c, "slot"))")
            case "pull_next_req":
                #expect(FreakProtocol.pullNextRequest(seq: seqByte(c)) == expect,
                        "pull_next_req seq \(int(c, "seq"))")
            case "go_frame":
                #expect(FreakProtocol.goFrame() == expect, "go_frame")
            case "open_write_frame":
                let got = try FreakProtocol.openWriteFrame(seq: seqByte(c),
                                                           slot: int(c, "slot"))
                #expect(got == expect, "open_write_frame slot \(int(c, "slot"))")
            case "name_write_frame":
                let got = try FreakProtocol.nameWriteFrame(
                    seq: seqByte(c), slot: int(c, "slot"),
                    name: str(c, "name"), meta: hexBytes(str(c, "meta")))
                #expect(got == expect, "name_write_frame slot \(int(c, "slot"))")
                let payload = [UInt8](FreakProtocol.parse(got)!.data)
                let ep = c["expected_payload"] as! [String: Any]
                #expect(Int(payload[3]) == int(ep, "p3"),
                        "payload[3] slot \(int(c, "slot"))")
                #expect(Int(payload[8]) == int(ep, "p8"),
                        "payload[8] slot \(int(c, "slot"))")
                #expect(Int(payload[9]) == int(ep, "p9"),
                        "payload[9] slot \(int(c, "slot"))")
            default:
                Issue.record("unhandled frames.json kind: \(kind)")
            }
        }
    }

    // -------------------------------------------------- name_replies.json

    @Test func nameReplies() throws {
        for c in try vectorCases("name_replies.json") {
            let payload = hexBytes(str(c, "payload"))
            let raw = hexBytes(str(c, "frame"))
            #expect(FreakProtocol.frame(seq: 0, length: 0x23,
                                        cmd: FreakProtocol.cmdName,
                                        data: payload) == raw)
            let f = try #require(FreakProtocol.parse(raw))
            #expect(f.seq == 0 && f.length == 0x23 && f.cmd == FreakProtocol.cmdName)
            #expect(f.data == payload)
            let info = try FreakProtocol.decodeNameReply(f)
            let expected = c["expected"] as! [String: Any]
            #expect(info.slot == int(expected, "slot"))
            #expect(info.name == str(expected, "name"))
            #expect(spacedHex(info.meta) == str(expected, "meta"))
        }
    }

    // --------------------------------------------------- write_burst.json

    @Test func writeBurst() throws {
        for c in try vectorCases("write_burst.json") {
            let slot = int(c, "slot")
            let blob = hexBytes(str(c, "blob_hex"))
            #expect(FreakProtocol.digest(blob) == str(c, "blob_sha256"),
                    "digest parity for slot \(slot)")
            let transcript = c["transcript"] as! [[String: Any]]
            let tt = TranscriptTransport(transcript: transcript)
            let session = makeSession(tt)
            let preset = try Preset(name: str(c, "name"), blob: blob,
                                    meta: hexBytes(str(c, "meta")))
            let info = try session.writePreset(slot: slot, preset)
            let readback = c["readback"] as! [String: Any]
            #expect(info.slot == int(readback, "slot"))
            #expect(info.name == str(readback, "name"))
            #expect(spacedHex(info.meta) == str(readback, "meta"))
            #expect(tt.mismatch == nil, "slot \(slot): \(tt.mismatch ?? "")")
            #expect(tt.fullyConsumed, "slot \(slot): transcript not fully consumed")
            // data-shape checks pinned by the file itself
            #expect(int(c, "chunk_count") == FreakProtocol.chunkCount)
            let ackCount = transcript.filter {
                str($0, "dir") == "in" && str($0, "label") == "ack"
            }.count
            #expect(ackCount == int(c, "expected_ack_count") && ackCount == 149)
            let chunkSeqs = (c["chunk_seqs"] as! [Any]).map { ($0 as! NSNumber).intValue }
            #expect(chunkSeqs == (0..<FreakProtocol.chunkCount).map { ($0 + 1) % 128 })
        }
    }

    // ----------------------------------------------------- read_dump.json

    @Test func readDump() throws {
        for c in try vectorCases("read_dump.json") {
            let slot = int(c, "slot")
            let transcript = c["transcript"] as! [[String: Any]]
            let tt = TranscriptTransport(transcript: transcript)
            let session = makeSession(tt)
            if let nameInfo = c["name_info"] as? [String: Any] {
                let info = try session.readName(slot: slot)
                #expect(info.slot == int(nameInfo, "slot"))
                #expect(info.name == str(nameInfo, "name"))
                #expect(spacedHex(info.meta) == str(nameInfo, "meta"))
            }
            let blob = try session.readBlob(slot: slot)
            #expect(blob == hexBytes(str(c, "blob_hex")), "slot \(slot) blob bytes")
            #expect(FreakProtocol.digest(blob) == str(c, "blob_sha256"))
            #expect(blob.count == FreakProtocol.blobSize)
            #expect(tt.mismatch == nil, "slot \(slot): \(tt.mismatch ?? "")")
            #expect(tt.fullyConsumed, "slot \(slot): transcript not fully consumed")
            // the recorded pull seqs are the transcript's outbound 0x18 seqs
            let pullSeqs = (c["pull_seqs"] as! [Any]).map { ($0 as! NSNumber).intValue }
            let transcriptPulls = transcript
                .filter { str($0, "dir") == "out" && str($0, "label") == "pull_next_req" }
                .map { int($0, "seq") }
            #expect(pullSeqs == transcriptPulls)
            #expect(pullSeqs.count == int(c, "chunk_count"))
            #expect(!pullSeqs.contains(0),
                    "the addressed session counter never emits seq 0")
        }
    }

    // ----------------------------------------------------- reply_lag.json

    @Test func replyLag() throws {
        for c in try vectorCases("reply_lag.json") {
            switch str(c, "kind") {
            case "raw_wire_lag":
                try runRawWireLag(c)
            case "session_scrambled_order":
                try runSessionScrambledOrder(c)
            default:
                Issue.record("unhandled reply_lag.json kind: \(str(c, "kind"))")
            }
        }
    }

    private func runRawWireLag(_ c: [String: Any]) throws {
        let sim = SimulatedMicroFreak.factoryFresh()
        #expect(sim.replyLag)
        let requests = c["requests"] as! [[String: Any]]
        let releases = c["reply_after_each_request"] as! [Any]
        #expect(requests.count == releases.count)
        for (request, release) in zip(requests, releases) {
            try sim.send(FreakProtocol.readNameRequest(seq: seqByte(request),
                                                       slot: int(request, "slot")))
            let raw = try sim.receive(timeout: 0.0)
            if let expected = release as? [String: Any] {
                let releasedRaw = try #require(raw)
                let f = try #require(FreakProtocol.parse(releasedRaw))
                let info = try FreakProtocol.decodeNameReply(f)
                #expect(info.slot == int(expected, "reply_slot"))
                #expect(info.name == str(expected, "name"))
                #expect(Int(f.seq) == int(expected, "reply_seq"))
            } else {
                #expect(raw == nil, "first reply must be held")
            }
        }
        expectWireLogMatches(sim.wireLog, c["transcript"] as! [[String: Any]],
                             context: "raw_wire_lag")
    }

    private func runSessionScrambledOrder(_ c: [String: Any]) throws {
        let sim = SimulatedMicroFreak.factoryFresh()
        let session = makeSession(sim)
        let readOrder = (c["read_order"] as! [Any]).map { ($0 as! NSNumber).intValue }
        let results = c["results"] as! [[String: Any]]
        #expect(readOrder.count == int(c, "reads"))
        #expect(readOrder.count == results.count)
        for (slot, expected) in zip(readOrder, results) {
            let info = try session.readName(slot: slot)
            #expect(info.slot == int(expected, "requested_slot"))
            #expect(info.name == str(expected, "name"), "slot \(slot)")
            #expect(spacedHex(info.meta) == str(expected, "meta"), "slot \(slot)")
        }
        #expect(sim.faults.isEmpty, "\(sim.faults)")
        let requestsSent = sim.wireLog.filter { entry in
            guard entry.direction == .out,
                  let f = FreakProtocol.parse(entry.raw) else { return false }
            return f.cmd == FreakProtocol.cmdOpen && f.data.count == 3
                && f.data.last == 0
        }.count
        #expect(requestsSent == int(c, "name_requests_sent"))
        #expect(requestsSent > readOrder.count, "the defense engaged")
        expectWireLogMatches(sim.wireLog, c["transcript"] as! [[String: Any]],
                             context: "session_scrambled_order")
    }

    // ----------------------------------------------------- sync_diff.json

    @Test func syncDiff() throws {
        for c in try vectorCases("sync_diff.json") {
            let name = str(c, "name")
            let records = slotRecords(c)
            let snapshot = DeviceSnapshot(
                takenAt: "2026-09-01T00:00:00", records: records,
                timing: TimingReport(totalSeconds: 0, perSlotSeconds: 0,
                                     nameMsMedian: nil, dumpMsMedian: nil))
            let entries = (c["library"] as! [[String: Any]]).enumerated().map { i, d in
                LibraryEntry(id: String(format: "lib%02d", i),
                             name: str(d, "name"), sha256: str(d, "sha256"),
                             metaHex: "080000000000000033",
                             slot: optInt(d, "slot"),
                             addedAt: "2026-09-01T00:00:00", tags: [])
            }
            let library = Library(root: URL(fileURLWithPath: "/unused-in-memory"),
                                  entries: entries)
            if let expectError = c["expect_error"] as? String {
                #expect(expectError == "ValueError")
                #expect(throws: FreakError.snapshotMissingHashes) {
                    try FreakCore.diff(snapshot, library)
                }
                continue
            }
            let result: SyncDiff
            if let threshold = optInt(c, "threshold") {
                result = try FreakCore.diff(snapshot, library, threshold: threshold)
            } else {
                result = try FreakCore.diff(snapshot, library)
            }
            let expected = c["expected"] as! [[String: Any]]
            #expect(result.slots.count == expected.count, "\(name)")
            for (row, exp) in zip(result.slots, expected) {
                #expect(row.slot == int(exp, "slot"), "\(name)")
                #expect(row.status.rawValue == str(exp, "status"),
                        "\(name): slot \(row.slot)")
                #expect(row.device.slot == row.slot, "\(name)")
            }
        }
    }

    // ---------------------------------------------------- expendable.json

    @Test func expendable() throws {
        for c in try vectorCases("expendable.json") {
            let name = str(c, "name")
            let records = slotRecords(c)
            let got: Set<Int>
            if let threshold = optInt(c, "threshold") {
                got = Analysis.findExpendable(records, threshold: threshold)
            } else {
                got = Analysis.findExpendable(records)
            }
            let expected = Set((c["expected_expendable"] as! [Any])
                .map { ($0 as! NSNumber).intValue })
            #expect(got == expected, "\(name)")
        }
    }
}
