// VectorTests.swift — the golden-vector runner. The vectors are generated by
// the Python reference implementation and are AUTHORITATIVE: the Swift port
// must produce and parse byte-identical frames. The runner enumerates every
// *.json in the vectors directory and FAILS if a file exists that it does
// not handle — a new vector file can never be silently skipped.

import Foundation
import Testing
@testable import FreakCore

private let handledFiles: Set<String> = [
    "device_state.json", "expendable.json", "frames.json",
    "name_replies.json", "read_dump.json", "reply_lag.json",
    "sync_diff.json", "write_burst.json", "write_conversation.json",
    // collections & categories vectors — consumed by CategoryAttributesTests
    // and CollectionsTests (not by this frame-transcript runner).
    "category.json", "library_attrs.json", "collections.json",
]

private func expectWireLogMatches(_ log: [WireLogEntry],
                                  _ transcript: [[String: Any]],
                                  context: String) {
    #expect(log.count == transcript.count,
            "\(context): wire log has \(log.count) entries, transcript \(transcript.count)")
    for (i, (entry, t)) in zip(log, transcript).enumerated() {
        #expect(entry.direction.rawValue == str(t, "dir"),
                "\(context): direction mismatch at entry \(i)")
        #expect(entry.raw == hexBytes(str(t, "frame")),
                "\(context): frame mismatch at entry \(i) (\(str(t, "label")))")
    }
}

@Suite("Golden vectors")
struct VectorTests {

    /// Safety net: every *.json in the vectors directory must have a runner;
    /// a missing expected file fails too.
    @Test func everyVectorFileIsHandled() throws {
        let files = try FileManager.default
            .contentsOfDirectory(atPath: Vectors.directory.path)
            .filter { $0.hasSuffix(".json") }
        for f in files where !handledFiles.contains(f) {
            Issue.record("vector file \(f) exists but the runner does not handle it — add a runner")
        }
        #expect(Set(files) == handledFiles)
    }

    // -------------------------------------------------------- frames.json

    @Test func frameBuilders() throws {
        let cases = try Vectors.cases("frames.json")
        #expect(!cases.isEmpty)
        for c in cases {
            let kind = str(c, "kind")
            // chunk_frames carries a "frames" list instead of one "frame"
            let expect = (c["frame"] as? String).map(hexBytes) ?? Data()
            switch kind {
            case "read_name_req":
                let got = try Wire.readNameRequest(seq: seqByte(c), slot: int(c, "slot"))
                #expect(got == expect, "read_name_req slot \(int(c, "slot"))")
            case "open_dump_req":
                let got = try Wire.openDumpRequest(seq: seqByte(c), slot: int(c, "slot"))
                #expect(got == expect, "open_dump_req slot \(int(c, "slot"))")
            case "pull_next_req":
                #expect(Wire.pullNextRequest(seq: seqByte(c)) == expect,
                        "pull_next_req seq \(int(c, "seq"))")
            case "go_frame":
                #expect(Wire.goFrame() == expect, "go_frame")
            case "open_write_frame":
                let got = try Wire.openWriteFrame(seq: seqByte(c), slot: int(c, "slot"))
                #expect(got == expect, "open_write_frame slot \(int(c, "slot"))")
            case "name_write_frame":
                let got = try Wire.nameWriteFrame(
                    seq: seqByte(c), slot: int(c, "slot"),
                    name: str(c, "name"), meta: hexBytes(str(c, "meta")))
                #expect(got == expect, "name_write_frame slot \(int(c, "slot"))")
                let payload = [UInt8](Wire.parse(got)!.data)
                let ep = c["expected_payload"] as! [String: Any]
                #expect(Int(payload[3]) == int(ep, "p3"), "payload[3] slot \(int(c, "slot"))")
                #expect(Int(payload[8]) == int(ep, "p8"), "payload[8] slot \(int(c, "slot"))")
                #expect(Int(payload[9]) == int(ep, "p9"), "payload[9] slot \(int(c, "slot"))")
            case "chunk_frames":
                let blob = hexBytes(str(c, "blob_hex"))
                #expect(Wire.digest(blob) == str(c, "blob_sha256"))
                let frames = try Wire.chunkFrames(blob: blob)
                let expected = (c["frames"] as! [Any]).map { hexBytes($0 as! String) }
                #expect(frames.count == int(c, "chunk_count"))
                #expect(frames.count == Wire.chunkCount)
                if let firstBad = zip(frames, expected).enumerated()
                    .first(where: { $1.0 != $1.1 })?.offset {
                    Issue.record("chunk_frames: first mismatch at chunk \(firstBad)")
                }
                #expect(frames == expected)
                let chunkSeqs = (c["chunk_seqs"] as! [Any]).map { ($0 as! NSNumber).intValue }
                #expect(frames.map { Int(Wire.parse($0)!.seq) } == chunkSeqs)
                #expect(chunkSeqs == (0..<Wire.chunkCount).map { ($0 + 1) % 128 },
                        "chunk seqs continue from the go frame's 0, wrapping THROUGH 0")
                for (i, raw) in frames.enumerated() {
                    let f = Wire.parse(raw)!
                    #expect(f.cmd == (i == frames.count - 1
                                      ? Wire.cmdChunkLast : Wire.cmdChunkMore),
                            "chunk \(i) cmd")
                    #expect(f.data.count == Wire.chunkSize, "chunk \(i) size")
                }
            default:
                Issue.record("unhandled frames.json kind: \(kind)")
            }
        }
    }

    // -------------------------------------------------- name_replies.json

    @Test func nameReplies() throws {
        for c in try Vectors.cases("name_replies.json") {
            let payload = hexBytes(str(c, "payload"))
            let raw = hexBytes(str(c, "frame"))
            #expect(Wire.frame(seq: 0, length: 0x23, cmd: Wire.cmdName,
                               data: payload) == raw)
            let f = try #require(Wire.parse(raw))
            #expect(f.seq == 0 && f.length == 0x23 && f.cmd == Wire.cmdName)
            #expect(f.data == payload)
            let info = try Wire.decodeNameReply(f)
            let expected = c["expected"] as! [String: Any]
            #expect(info.slot == int(expected, "slot"))
            #expect(info.name == str(expected, "name"))
            #expect(spacedHex(info.meta) == str(expected, "meta"))
        }
    }

    // --------------------------------------------------- write_burst.json

    @Test func writeBurst() async throws {
        for c in try Vectors.cases("write_burst.json") {
            let slot = int(c, "slot")
            let blob = hexBytes(str(c, "blob_hex"))
            #expect(Wire.digest(blob) == str(c, "blob_sha256"),
                    "digest parity for slot \(slot)")
            let transcript = c["transcript"] as! [[String: Any]]
            let tt = transcriptTransport(transcript)
            let session = makeSession(tt)
            let preset = try Preset(name: str(c, "name"), blob: blob,
                                    meta: hexBytes(str(c, "meta")))
            let info = try await session.writePreset(slot: slot, preset: preset)
            let readback = c["readback"] as! [String: Any]
            #expect(info.slot == int(readback, "slot"))
            #expect(info.name == str(readback, "name"))
            #expect(spacedHex(info.meta) == str(readback, "meta"))
            let mismatch = await tt.mismatch
            #expect(mismatch == nil, "slot \(slot): \(mismatch ?? "")")
            #expect(await tt.fullyConsumed, "slot \(slot): transcript not fully consumed")
            // data-shape checks pinned by the file itself
            #expect(int(c, "chunk_count") == Wire.chunkCount)
            let ackCount = transcript.filter {
                str($0, "dir") == "in" && str($0, "label") == "ack"
            }.count
            #expect(ackCount == int(c, "expected_ack_count") && ackCount == 149)
            let chunkSeqs = (c["chunk_seqs"] as! [Any]).map { ($0 as! NSNumber).intValue }
            #expect(chunkSeqs == (0..<Wire.chunkCount).map { ($0 + 1) % 128 })
        }
    }

    // -------------------------------------------- write_conversation.json

    /// A complete VERIFIED write — MicroFreakDevice.write (7-frame gate
    /// sequence, then name + blob read-back with hash compare) replayed step
    /// by step against the reference transcript.
    @Test func writeConversation() async throws {
        for c in try Vectors.cases("write_conversation.json") {
            let slot = int(c, "slot")
            let blob = hexBytes(str(c, "blob_hex"))
            #expect(Wire.digest(blob) == str(c, "blob_sha256"),
                    "digest parity for slot \(slot)")
            let transcript = c["transcript"] as! [[String: Any]]
            let tt = transcriptTransport(transcript)
            let device = makeDevice(tt)
            let preset = try Preset(name: str(c, "name"), blob: blob,
                                    meta: hexBytes(str(c, "meta")))
            let report = try await device.write(slot: slot, preset: preset)
            let expected = c["report"] as! [String: Any]
            #expect(report.slot == int(expected, "slot"))
            #expect(report.sha256 == str(expected, "sha256"))
            #expect(report.name == str(expected, "name"))
            #expect(report.verified == true)
            let mismatch = await tt.mismatch
            #expect(mismatch == nil, "slot \(slot): \(mismatch ?? "")")
            #expect(await tt.fullyConsumed, "slot \(slot): transcript not fully consumed")
            // data-shape checks pinned by the file itself
            let counts = c["counts"] as! [String: Any]
            let outs = transcript.filter { str($0, "dir") == "out" }.count
            let ins = transcript.filter { str($0, "dir") == "in" }.count
            #expect(outs == int(counts, "out_frames") && outs == 298)
            #expect(ins == int(counts, "in_frames") && ins == 297)
            let acks = transcript.filter {
                str($0, "dir") == "in" && str($0, "label") == "ack"
            }.count
            #expect(acks == int(counts, "write_acks") && acks == 149)
        }
    }

    // --------------------------------------------------- device_state.json

    /// The full 512-slot factory state: Swift's factoryFresh must reproduce
    /// the Python sim's every name, blob sha and meta byte (pinning synthBlob
    /// parity), and the analysis layer must judge exactly the init zone
    /// expendable — content-based, never a name == "Init" match.
    @Test func deviceState() async throws {
        for c in try Vectors.cases("device_state.json") {
            let slots = int(c, "slots")
            let sim = SimulatedMicroFreak.factoryFresh(
                initCopies: int(c, "init_copies"), seed: int(c, "seed"), slots: slots)
            let state = c["state"] as! [String: [String: Any]]
            #expect(state.count == slots)
            let initSha = str(c, "init_blob_sha256")
            #expect(Wire.digest(SimulatedMicroFreak.synthBlob(
                seed: int(c, "seed"), label: "init")) == initSha)
            var records: [SlotRecord] = []
            var shas = Set<String>()
            var mismatches = 0
            for slot in 0..<slots {
                let expected = state[String(format: "%03d", slot)]!
                let pr = try await sim.peek(slot: slot)
                let sha = Wire.digest(pr.blob)
                if pr.name != str(expected, "name")
                    || sha != str(expected, "sha256")
                    || spacedHex(pr.meta) != str(expected, "meta") {
                    mismatches += 1
                    if mismatches <= 3 {
                        let got = "(\(pr.name), \(sha), \(spacedHex(pr.meta)))"
                        let want = "(\(str(expected, "name")), \(str(expected, "sha256")), \(str(expected, "meta")))"
                        Issue.record("slot \(slot): got \(got), vector expects \(want)")
                    }
                }
                shas.insert(sha)
                records.append(SlotRecord(slot: slot, name: pr.name,
                                          sha256: sha, meta: pr.meta, blob: nil))
            }
            #expect(mismatches == 0, "\(mismatches) slots differ from the reference state")
            #expect(shas.count == int(c, "distinct_sha_count"))
            let named = int(c, "named_slots")
            #expect(records[named].sha256 == initSha
                    && records[named - 1].sha256 != initSha,
                    "the named/init boundary sits at slot \(named)")
            let exp = c["expected_expendable"] as! [String: Any]
            let first = int(exp, "first_slot")
            let count = int(exp, "count")
            #expect(Analysis.findExpendable(records) == Set(first..<(first + count)),
                    "expendable set must be exactly the init zone")
        }
    }

    // ----------------------------------------------------- read_dump.json

    @Test func readDump() async throws {
        for c in try Vectors.cases("read_dump.json") {
            let slot = int(c, "slot")
            let transcript = c["transcript"] as! [[String: Any]]
            let tt = transcriptTransport(transcript)
            let session = makeSession(tt)
            if let nameInfo = c["name_info"] as? [String: Any] {
                let info = try await session.readName(slot: slot)
                #expect(info.slot == int(nameInfo, "slot"))
                #expect(info.name == str(nameInfo, "name"))
                #expect(spacedHex(info.meta) == str(nameInfo, "meta"))
            }
            let blob = try await session.readBlob(slot: slot)
            #expect(blob == hexBytes(str(c, "blob_hex")), "slot \(slot) blob bytes")
            #expect(Wire.digest(blob) == str(c, "blob_sha256"))
            #expect(blob.count == Wire.blobSize)
            let mismatch = await tt.mismatch
            #expect(mismatch == nil, "slot \(slot): \(mismatch ?? "")")
            #expect(await tt.fullyConsumed, "slot \(slot): transcript not fully consumed")
            // the recorded pull seqs are the transcript's outbound 0x18 seqs
            let pullSeqs = (c["pull_seqs"] as! [Any]).map { ($0 as! NSNumber).intValue }
            let transcriptPulls = transcript
                .filter { str($0, "dir") == "out" && str($0, "label") == "pull_next_req" }
                .map { int($0, "seq") }
            #expect(pullSeqs == transcriptPulls)
            #expect(pullSeqs.count == int(c, "chunk_count"))
            #expect(!pullSeqs.contains(0),
                    "the addressed session counter never emits seq 0")
        }
    }

    // ----------------------------------------------------- reply_lag.json

    @Test func replyLag() async throws {
        for c in try Vectors.cases("reply_lag.json") {
            switch str(c, "kind") {
            case "raw_wire_lag":
                try await runRawWireLag(c)
            case "session_scrambled_order":
                try await runSessionScrambledOrder(c)
            default:
                Issue.record("unhandled reply_lag.json kind: \(str(c, "kind"))")
            }
        }
    }

    private func runRawWireLag(_ c: [String: Any]) async throws {
        let sim = SimulatedMicroFreak.factoryFresh()
        #expect(sim.replyLag)
        let requests = c["requests"] as! [[String: Any]]
        let releases = c["reply_after_each_request"] as! [Any]
        #expect(requests.count == releases.count)
        for (request, release) in zip(requests, releases) {
            try await sim.send(Wire.readNameRequest(seq: seqByte(request),
                                                    slot: int(request, "slot")))
            let raw = try await sim.receive(timeout: 0.0)
            if let expected = release as? [String: Any] {
                let releasedRaw = try #require(raw)
                let f = try #require(Wire.parse(releasedRaw))
                let info = try Wire.decodeNameReply(f)
                #expect(info.slot == int(expected, "reply_slot"))
                #expect(info.name == str(expected, "name"))
                #expect(Int(f.seq) == int(expected, "reply_seq"))
            } else {
                #expect(raw == nil, "first reply must be held")
            }
        }
        expectWireLogMatches(await sim.wireLog(),
                             c["transcript"] as! [[String: Any]],
                             context: "raw_wire_lag")
    }

    private func runSessionScrambledOrder(_ c: [String: Any]) async throws {
        let sim = SimulatedMicroFreak.factoryFresh()
        let session = makeSession(sim)
        let readOrder = (c["read_order"] as! [Any]).map { ($0 as! NSNumber).intValue }
        let results = c["results"] as! [[String: Any]]
        #expect(readOrder.count == int(c, "reads"))
        #expect(readOrder.count == results.count)
        for (slot, expected) in zip(readOrder, results) {
            let info = try await session.readName(slot: slot)
            #expect(info.slot == int(expected, "requested_slot"))
            #expect(info.name == str(expected, "name"), "slot \(slot)")
            #expect(spacedHex(info.meta) == str(expected, "meta"), "slot \(slot)")
        }
        let faults = await sim.faults()
        #expect(faults.isEmpty, "\(faults)")
        let wireLog = await sim.wireLog()
        let requestsSent = wireLog.filter { entry in
            guard entry.direction == .out, let f = Wire.parse(entry.raw) else { return false }
            return f.cmd == Wire.cmdOpen && f.data.count == 3 && f.data.last == 0
        }.count
        #expect(requestsSent == int(c, "name_requests_sent"))
        #expect(requestsSent > readOrder.count, "the defense engaged")
        expectWireLogMatches(wireLog, c["transcript"] as! [[String: Any]],
                             context: "session_scrambled_order")
    }

    // ----------------------------------------------------- sync_diff.json

    @Test func syncDiff() throws {
        for c in try Vectors.cases("sync_diff.json") {
            let name = str(c, "name")
            let records = slotRecords(c)
            let snapshot = DeviceSnapshot(
                takenAt: "2026-09-01T00:00:00", records: records,
                timing: TimingReport(totalSeconds: 0, perSlotSeconds: 0,
                                     nameMsMedian: nil, dumpMsMedian: nil))
            var baseline: [Int: PresetRef] = [:]
            for d in (c["baseline"] as! [[String: Any]]) {
                baseline[int(d, "slot")] = PresetRef(
                    sha256: str(d, "sha256"), name: str(d, "name"),
                    metaHex: str(d, "meta_hex"))
            }
            if let expectError = c["expect_error"] as? String {
                #expect(expectError == "ValueError")
                #expect(throws: FreakError.snapshotMissingHashes) {
                    try computeDiff(snapshot: snapshot, baseline: baseline)
                }
                continue
            }
            let result: SyncDiff
            if let threshold = optInt(c, "threshold") {
                result = try computeDiff(snapshot: snapshot, baseline: baseline,
                                         threshold: threshold)
            } else {
                result = try computeDiff(snapshot: snapshot, baseline: baseline)
            }
            let expected = c["expected"] as! [[String: Any]]
            #expect(result.slots.count == expected.count, "\(name)")
            for (row, exp) in zip(result.slots, expected) {
                #expect(row.slot == int(exp, "slot"), "\(name)")
                #expect(row.status.rawValue == str(exp, "status"),
                        "\(name): slot \(row.slot)")
                #expect(row.nameDiffers == bool(exp, "name_differs"),
                        "\(name): slot \(row.slot)")
                #expect(row.device?.slot == row.slot, "\(name)")
            }
            let unread = (c["unread_baseline_slots"] as! [Any])
                .map { ($0 as! NSNumber).intValue }
            #expect(result.unreadBaselineSlots == unread, "\(name)")
        }
    }

    // ---------------------------------------------------- expendable.json

    @Test func expendable() throws {
        for c in try Vectors.cases("expendable.json") {
            let name = str(c, "name")
            let records = slotRecords(c)
            let got: Set<Int>
            if let threshold = optInt(c, "threshold") {
                got = Analysis.findExpendable(records, threshold: threshold)
            } else {
                got = Analysis.findExpendable(records)
            }
            let expected = Set((c["expected_expendable"] as! [Any])
                .map { ($0 as! NSNumber).intValue })
            #expect(got == expected, "\(name)")
        }
    }
}
