// Vectors.swift — golden-vector loading. The vectors under Fixtures/vectors/
// are generated by the Python reference implementation (tools/gen_vectors.py)
// and are AUTHORITATIVE: byte-for-byte wire parity. Swift only consumes
// them — it never regenerates or reshapes them, and no expected bytes are
// hand-written in Swift tests.
//
// Every file is {"description": str, "cases": [...]}, with all byte
// sequences space-separated uppercase hex ("F0 00 20 6B ..."). A missing or
// unparseable fixture file is a test FAILURE, never a skip.

import Foundation
import Testing
@testable import FreakCore

enum Vectors {
    static var directory: URL {
        Bundle.module.resourceURL!
            .appendingPathComponent("Fixtures")
            .appendingPathComponent("vectors")
    }

    /// Loads Fixtures/vectors/<file> and returns its cases. Throws (fails
    /// the test) if missing or unparseable.
    static func cases(_ file: String) throws -> [[String: Any]] {
        let data = try Data(contentsOf: directory.appendingPathComponent(file))
        let obj = try JSONSerialization.jsonObject(with: data) as! [String: Any]
        return obj["cases"] as! [[String: Any]]
    }
}

func int(_ c: [String: Any], _ key: String) -> Int {
    (c[key] as! NSNumber).intValue
}

func optInt(_ c: [String: Any], _ key: String) -> Int? {
    (c[key] as? NSNumber)?.intValue
}

func str(_ c: [String: Any], _ key: String) -> String {
    c[key] as! String
}

func seqByte(_ c: [String: Any]) -> UInt8 {
    UInt8(int(c, "seq"))
}

func slotRecords(_ c: [String: Any]) -> [SlotRecord] {
    (c["records"] as! [[String: Any]]).map {
        SlotRecord(slot: int($0, "slot"), name: $0["name"] as? String,
                   sha256: $0["sha256"] as? String, meta: nil, blob: nil)
    }
}
