// MFProjzImportTests.swift — golden coverage for the Swift .mfprojz/.mbp
// reader (App/Sources/Support/MFProjzImport.swift), a port of the VERIFIED
// tools/mbp_import.py. The fixture Fixtures/bank_import.json is generated by
// tools/gen_vectors.py: its 'expected' values come from the reference Python
// parser, so this test pins the port — the Boost text tokenizer, the latin-1
// decode, the hex-meta decode, the sub-bank slot map, and the hand-rolled
// Zip reader (a real DEFLATE member and a STORED member) — byte-for-byte
// against the reference (ux-spec-collections.md §29 open question 5).
//
// The fixture is loaded from disk relative to this source file (#filePath),
// so no test-bundle resource wiring is needed and it works wherever the
// checkout lives.

import XCTest
import CryptoKit
import FreakCore
@testable import FreakLibrarian

final class MFProjzImportTests: XCTestCase {

    private func fixture() throws -> [String: Any] {
        let url = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures/bank_import.json")
        let data = try Data(contentsOf: url)
        return try XCTUnwrap(
            JSONSerialization.jsonObject(with: data) as? [String: Any])
    }

    private func sha256Hex(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    private func metaHex(_ data: Data) -> String {
        data.map { String(format: "%02x", $0) }.joined()
    }

    /// One BankItem must match the reference parser's recorded output exactly.
    private func assertMatches(_ item: BankItem,
                               _ expected: [String: Any]) throws {
        XCTAssertEqual(item.slot, expected["slot"] as? Int)
        XCTAssertEqual(item.name, try XCTUnwrap(expected["name"] as? String))
        XCTAssertEqual(metaHex(item.meta),
                       try XCTUnwrap(expected["meta_hex"] as? String))
        if let sha = expected["blob_sha256"] as? String {
            let blob = try XCTUnwrap(item.blob,
                                     "expected a blob for \(item.name)")
            XCTAssertEqual(blob.count, MFProjzImport.blobSize)
            XCTAssertEqual(sha256Hex(blob), sha)
        } else {
            XCTAssertNil(item.blob, "expected an empty slot for \(item.name)")
        }
    }

    func testParsesStandaloneMbp() throws {
        let fx = try fixture()
        let m = try XCTUnwrap(fx["mbp"] as? [String: Any])
        let bytes = try XCTUnwrap(
            Data(base64Encoded: try XCTUnwrap(m["bytes_b64"] as? String)))
        let items = try MFProjzImport.parse(
            data: bytes, filename: try XCTUnwrap(m["filename"] as? String))
        XCTAssertEqual(items.count, 1)
        try assertMatches(items[0], try XCTUnwrap(m["expected"] as? [String: Any]))
    }

    func testParsesMfprojzBank() throws {
        let fx = try fixture()
        let z = try XCTUnwrap(fx["mfprojz"] as? [String: Any])
        let bytes = try XCTUnwrap(
            Data(base64Encoded: try XCTUnwrap(z["bytes_b64"] as? String)))
        let items = try MFProjzImport.parse(
            data: bytes, filename: try XCTUnwrap(z["filename"] as? String))
        let expected = try XCTUnwrap(z["expected"] as? [[String: Any]])
        // The non-.mbp file in the archive is ignored; every real member is
        // returned, in sorted-filename order.
        XCTAssertEqual(items.count, expected.count)
        for (item, exp) in zip(items, expected) {
            try assertMatches(item, exp)
        }
    }

    /// A file that is neither a .mbp archive nor a readable .mfprojz Zip is a
    /// clean protocolViolation, never a crash.
    func testRejectsNonBankFile() {
        let junk = Data("not a bank".utf8)
        XCTAssertThrowsError(
            try MFProjzImport.parse(data: junk, filename: "notes.txt"))
        XCTAssertThrowsError(
            try MFProjzImport.parse(data: junk, filename: "broken.mfprojz"))
    }
}
